### PR TITLE
use Decompress directly without ioutil.ReadAll

### PR DESCRIPTION
**Pull request by dqminh**
Decompress guess the size first then decompress so generally it takes much
less allocation than iotuil.ReadAll which used a fixed buffer size of 512 bytes
when message size is larger than 512 bytes.

Creating ztsd.Reader for small messages is also costly because it
has to perform additional cgo calls to initialize the context, compare to just 2
cgo call to decompress with a nil dst slice.

See some benchmark in https://gist.github.com/dqminh/b8d46a164ccad105b5a523c5050ab021

### CODE REVIEW

**Comment by dqminh** [comment]
Probably make sense to change Compress too, but i'm going to test this first.

**Comment by bobrik** [comment]
I rebased my branch on top of master to remove extra commits from this PR, but now you have conflicts.

To be clear, we're switching from the first to the second, right?

```
BenchmarkDataDogZstdReadAll-4                      50000             26652 ns/op          285088 B/op         15 allocs/op
BenchmarkDataDogZstdDecompress-4                 2000000               905 ns/op            4144 B/op          3 allocs/op
```

Any reason not to go to this:

```
BenchmarkDataDogZstdDecompressLargeBuffer-4      2000000               748 ns/op            4096 B/op          1 allocs/op
```

LGTM in general, very nice improvements.

**Comment by dqminh** [comment]
`BenchmarkDataDogZstdDecompressLargeBuffer-4 ` allocates a larger buffer such that its enough to decompress without further reallocation. I think its workload dependant which is why its not enabled yet.

I think its probably more helpful to look at sync.Pool instead, it should help when we consume messages at higher rate.

**Comment by dqminh** [comment]
I think this should be good to go.

**Pull request merged**
